name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  # push:
  #   branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
    
    defaults:
        run:
          working-directory: source

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.0.1
          terraform_wrapper: false
        
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform apply to dev
      if: github.event.inputs.terraform_action == 'apply'
      run: terraform apply -auto-approve

    - name: Terraform destroy dev
      if: github.event.inputs.terraform_action == 'destroy'
      run: terraform destroy -auto-approve
